Attribute VB_Name = "NATCheckCore"
' NAT - order check inside Word (offline, no Python).
'
' Macro: NAT_CheckOrderOffline - checks the active document and marks it:
'   red highlight + comment  = error, yellow highlight + comment = warning.
' Checks: item numbering, RNOKPP (check digit, birth date, sex), rank vs
' nomenclature (dismissal not above the limit; naval ranks not checked). Unknown words in positions -
' only when check.spelling=1 in nat_rules.txt (off: too many warnings on real orders).
'
' All Ukrainian texts, patterns and dictionaries live in nat_rules.txt (UTF-8):
' Word imports .bas files in the ANSI code page, so this file is ASCII only.
' nat_rules.txt is generated by scripts/word_macro/build_rules.py.
'
' The block between NAT CORE BEGIN / END is written in the common subset of VBA
' and VBScript (no types, no IIf/Val/Format/Optional): the project tests run
' it with cscript and compare the result with the program (tests/test_word_macro.py).
Option Explicit

'=== NAT CORE BEGIN ===
Function NAT_ReadUtf8(ByVal path)
    Dim st, text
    Set st = CreateObject("ADODB.Stream")
    st.Type = 2
    st.Charset = "utf-8"
    st.Open
    st.LoadFromFile path
    text = st.ReadText(-1)
    st.Close
    If Len(text) > 0 Then
        If AscW(Left(text, 1)) = &HFEFF Then text = Mid(text, 2)
    End If
    NAT_ReadUtf8 = text
End Function

Sub NAT_WriteUtf8(ByVal path, ByVal text)
    Dim st
    Set st = CreateObject("ADODB.Stream")
    st.Type = 2
    st.Charset = "utf-8"
    st.Open
    st.WriteText text
    st.SaveToFile path, 2
    st.Close
End Sub

Function NAT_LoadRules(ByVal path)
    Dim rules, vocab, words, text, lines, i, ln, p, key, value, n
    Set rules = CreateObject("Scripting.Dictionary")
    Set vocab = CreateObject("Scripting.Dictionary")
    Set words = CreateObject("Scripting.Dictionary")
    text = Replace(NAT_ReadUtf8(path), vbCr, "")
    lines = Split(text, vbLf)
    For i = 0 To UBound(lines)
        ln = lines(i)
        p = InStr(ln, "=")
        If Len(ln) > 0 And Left(ln, 1) <> "#" And p > 1 Then
            key = Left(ln, p - 1)
            value = Mid(ln, p + 1)
            If key = "v" Then
                vocab(value) = 1
            ElseIf key = "w" Then
                words(value) = 1
            ElseIf key = "rank" Or key = "limit" Or key = "month" Then
                n = rules(key & ".count") + 1
                rules(key & ".count") = n
                rules(key & "." & n) = value
            Else
                rules(key) = value
            End If
        End If
    Next
    rules.Add "vocab", vocab
    rules.Add "words", words
    Set NAT_LoadRules = rules
End Function

Function NAT_Msg(rules, ByVal key, args)
    Dim s, i
    s = Replace(rules("msg." & key), "\n", vbLf)
    For i = 0 To UBound(args)
        s = Replace(s, "{" & i & "}", CStr(args(i)))
    Next
    NAT_Msg = s
End Function

Function NAT_Re(ByVal pattern, ByVal ignoreCase)
    Dim r
    Set r = CreateObject("VBScript.RegExp")
    r.Pattern = pattern
    r.IgnoreCase = ignoreCase
    r.Global = True
    r.MultiLine = False
    Set NAT_Re = r
End Function

Function NAT_IsSpace(ByVal ch)
    Dim c
    c = AscW(ch)
    If c < 0 Then c = c + 65536
    NAT_IsSpace = (c >= 9 And c <= 13) Or (c >= 28 And c <= 32) Or c = 133 Or c = 160 _
        Or c = 5760 Or (c >= 8192 And c <= 8202) Or c = 8232 Or c = 8233 Or c = 8239 _
        Or c = 8287 Or c = 12288
End Function

Function NAT_Strip(ByVal s)
    Do While Len(s) > 0
        If Not NAT_IsSpace(Left(s, 1)) Then Exit Do
        s = Mid(s, 2)
    Loop
    Do While Len(s) > 0
        If Not NAT_IsSpace(Right(s, 1)) Then Exit Do
        s = Left(s, Len(s) - 1)
    Loop
    NAT_Strip = s
End Function

Function NAT_StripChars(ByVal s, ByVal chars)
    Do While Len(s) > 0
        If InStr(chars, Left(s, 1)) = 0 Then Exit Do
        s = Mid(s, 2)
    Loop
    Do While Len(s) > 0
        If InStr(chars, Right(s, 1)) = 0 Then Exit Do
        s = Left(s, Len(s) - 1)
    Loop
    NAT_StripChars = s
End Function

' Same as order_index.extractor.normalize_space: invisible chars out, whitespace collapsed.
Function NAT_NormalizeSpace(ByVal s)
    Dim i, ch, out, pendingSpace
    s = Replace(s, ChrW(&HAD), "")
    s = Replace(s, ChrW(&H200B), "")
    s = Replace(s, ChrW(&HFEFF), "")
    out = ""
    pendingSpace = False
    For i = 1 To Len(s)
        ch = Mid(s, i, 1)
        If NAT_IsSpace(ch) Then
            pendingSpace = True
        Else
            If pendingSpace And Len(out) > 0 Then out = out & " "
            pendingSpace = False
            out = out & ch
        End If
    Next
    NAT_NormalizeSpace = out
End Function

' Python str.splitlines(): every Word line break becomes its own line.
Function NAT_SplitLines(ByVal text)
    Dim marks, i
    text = Replace(text, vbCrLf, vbLf)
    marks = Array(13, 11, 12, 28, 29, 30, 133, 8232, 8233)
    For i = 0 To UBound(marks)
        text = Replace(text, ChrW(marks(i)), vbLf)
    Next
    If Right(text, 1) = vbLf Then text = Left(text, Len(text) - 1)
    NAT_SplitLines = Split(text, vbLf)
End Function

Function NAT_JoinRange(lines, ByVal first, ByVal last, ByVal sep)
    Dim i, out
    out = ""
    For i = first To last
        If i > first Then out = out & sep
        out = out & lines(i)
    Next
    NAT_JoinRange = out
End Function

' Same as order_index.position_dictionary.stem: case ending cut per hyphen part.
Function NAT_Stem(rules, ByVal word)
    Dim parts, endings, i, j, part, e
    If word = "-" Or word = ChrW(&H2013) Or word = ChrW(&H2014) Then
        NAT_Stem = "-"
        Exit Function
    End If
    word = LCase(word)
    word = Replace(word, ChrW(&H2019), "'")
    word = Replace(word, ChrW(&H2BC), "'")
    word = Replace(word, "`", "'")
    parts = Split(word, "-")
    endings = Split(rules("endings"), "|")
    For i = 0 To UBound(parts)
        part = parts(i)
        For j = 0 To UBound(endings)
            e = endings(j)
            If Len(part) - Len(e) >= 2 Then
                If Right(part, Len(e)) = e Then
                    part = Left(part, Len(part) - Len(e))
                    Exit For
                End If
            End If
        Next
        parts(i) = part
    Next
    NAT_Stem = Join(parts, "-")
End Function

Function NAT_Stems(rules, ByVal text)
    Dim re, m, out
    Set re = NAT_Re(rules("pattern.word"), False)
    out = ""
    For Each m In re.Execute(LCase(NAT_NormalizeSpace(text)))
        out = out & " " & NAT_Stem(rules, m.Value)
    Next
    out = Trim(out)
    If out = "" Then
        NAT_Stems = Array()
    Else
        NAT_Stems = Split(out, " ")
    End If
End Function

' Rank level from shpk_levels (soldier = 1 ... general = 21); -1 when not a rank.
Function NAT_RankLevel(rules, ByVal text)
    Dim words, n, i, parts, rankName, m, k, ok
    NAT_RankLevel = -1
    words = NAT_Stems(rules, text)
    n = UBound(words) + 1
    For i = 1 To rules("rank.count")
        parts = Split(rules("rank." & i), "|")
        rankName = Split(parts(0), " ")
        m = UBound(rankName) + 1
        If m > 0 And m <= n Then
            ok = True
            For k = 0 To m - 1
                If words(n - m + k) <> rankName(k) Then
                    ok = False
                    Exit For
                End If
            Next
            If ok Then
                NAT_RankLevel = CLng(parts(1))
                Exit Function
            End If
        End If
    Next
End Function

' Same as message_order.find_content_start_line.
Function NAT_ContentStart(rules, lines)
    Dim i, clean, markers, j, reNum
    Set reNum = NAT_Re("^[0-9]+[.)]", False)
    markers = Split(rules("content_markers"), "|")
    NAT_ContentStart = 0
    For i = 0 To UBound(lines)
        clean = NAT_Strip(lines(i))
        If Left(clean, 1) = ChrW(167) Or reNum.Test(clean) Then
            NAT_ContentStart = i
            Exit Function
        End If
        For j = 0 To UBound(markers)
            If InStr(UCase(clean), markers(j)) > 0 Then
                NAT_ContentStart = i
                Exit Function
            End If
        Next
    Next
End Function

Sub NAT_Add(findings, ByVal level, ByVal rule, ByVal where, ByVal what, ByVal how, ByVal q1, ByVal q2)
    Dim fields, i
    fields = Array(level, rule, where, what, how, q1, q2)
    For i = 0 To UBound(fields)
        fields(i) = Replace(Replace(Replace(CStr(fields(i)), vbTab, " "), vbCr, " "), vbLf, " ")
    Next
    findings.Add findings.Count, Join(fields, vbTab)
End Sub

Function NAT_Place(rules, ByVal label)
    If label = "" Then
        NAT_Place = NAT_Msg(rules, "where.item_none", Array())
    Else
        NAT_Place = NAT_Msg(rules, "where.item", Array(label))
    End If
End Function

' ---------------------------------------------------------------- numbering
Sub NAT_CheckNumbering(rules, lines, findings)
    Dim reItem, reGlued, start, i, clean, label, m, parts, number, previousTop
    Dim subCounters, parent, expected, errorLevel, warnLevel, rule, where, q, k, how
    Set reItem = NAT_Re(rules("pattern.item"), False)
    Set reGlued = NAT_Re(rules("pattern.glued"), False)
    Set subCounters = CreateObject("Scripting.Dictionary")
    errorLevel = NAT_Msg(rules, "level.error", Array())
    warnLevel = NAT_Msg(rules, "level.warning", Array())
    rule = NAT_Msg(rules, "num.rule", Array())
    start = NAT_ContentStart(rules, lines)
    previousTop = 0
    For i = start To UBound(lines)
        clean = NAT_Strip(lines(i))
        label = ""
        If Left(clean, 1) = ChrW(167) Then
            ' section line: numbering continues
        Else
            If reGlued.Test(clean) Then
                Set m = reGlued.Execute(clean)(0)
                label = m.SubMatches(0)
                NAT_Add findings, warnLevel, rule, NAT_Msg(rules, "where.item", Array(label)), _
                    NAT_Msg(rules, "num.glued.what", Array()), NAT_Msg(rules, "num.glued.how", Array()), _
                    Left(clean, 60), ""
            ElseIf reItem.Test(clean) Then
                label = reItem.Execute(clean)(0).SubMatches(0)
            End If
        End If
        If label <> "" Then
            parts = Split(label, ".")
            where = NAT_Msg(rules, "where.item", Array(label))
            q = Left(clean, 60)
            If UBound(parts) = 0 Then
                number = CLng(parts(0))
                ' Numbering runs through the whole order: a section does not restart it.
                If number = previousTop Then
                    NAT_Add findings, errorLevel, rule, where, NAT_Msg(rules, "num.dup.what", Array()), _
                        NAT_Msg(rules, "num.dup.how", Array(previousTop, previousTop + 1)), q, ""
                ElseIf number <> previousTop + 1 Then
                    how = NAT_Msg(rules, "num.gap.how", Array(previousTop + 1))
                    NAT_Add findings, errorLevel, rule, where, _
                        NAT_Msg(rules, "num.gap.what", Array(previousTop, number)), how, q, ""
                End If
                previousTop = number
            Else
                parent = ""
                For k = 0 To UBound(parts) - 1
                    If k > 0 Then parent = parent & "."
                    parent = parent & CLng(parts(k))
                Next
                If CLng(parts(0)) <> previousTop Then
                    NAT_Add findings, errorLevel, rule, where, _
                        NAT_Msg(rules, "num.sub_parent.what", Array(CLng(parts(0)))), _
                        NAT_Msg(rules, "num.sub_parent.how", Array(label, CLng(parts(0)))), q, ""
                End If
                expected = subCounters(parent) + 1
                If CLng(parts(UBound(parts))) <> expected Then
                    NAT_Add findings, errorLevel, rule, where, _
                        NAT_Msg(rules, "num.sub_seq.what", Array(parent, expected)), _
                        NAT_Msg(rules, "num.sub_seq.how", Array()), q, ""
                End If
                subCounters(parent) = CLng(parts(UBound(parts)))
            End If
        End If
    Next
End Sub

' ---------------------------------------------------------------- RNOKPP
Function NAT_IpnValid(ByVal token)
    Dim weights, s, i, r
    weights = Array(-1, 5, 7, 9, 4, 6, 10, 5, 7)
    s = 0
    For i = 0 To 8
        s = s + CLng(Mid(token, i + 1, 1)) * weights(i)
    Next
    r = s Mod 11
    If r < 0 Then r = r + 11
    NAT_IpnValid = ((r Mod 10) = CLng(Mid(token, 10, 1)))
End Function

Function NAT_DateKey(ByVal y, ByVal m, ByVal d)
    Dim dt
    NAT_DateKey = ""
    If m < 1 Or m > 12 Or d < 1 Or d > 31 Then Exit Function
    dt = DateSerial(y, m, d)
    If Year(dt) <> CLng(y) Or Month(dt) <> CLng(m) Or Day(dt) <> CLng(d) Then Exit Function
    NAT_DateKey = Right("0" & d, 2) & "." & Right("0" & m, 2) & "." & y
End Function

Function NAT_MonthNumber(rules, ByVal mName)
    Dim i, parts
    NAT_MonthNumber = 0
    For i = 1 To rules("month.count")
        parts = Split(rules("month." & i), "|")
        If parts(0) = mName Then NAT_MonthNumber = CLng(parts(1))
    Next
End Function

Sub NAT_CheckItemIpn(rules, ByVal label, ByVal body, findings)
    Dim low, dates, years, verbs, m, key, reToken, token, days, birth, sexMale, where, onlyDate, onlyYear, verb
    Dim errorLevel, warnLevel, rule, monthNo, keys
    errorLevel = NAT_Msg(rules, "level.error", Array())
    warnLevel = NAT_Msg(rules, "level.warning", Array())
    rule = NAT_Msg(rules, "ipn.rule", Array())
    Set dates = CreateObject("Scripting.Dictionary")
    Set years = CreateObject("Scripting.Dictionary")
    Set verbs = CreateObject("Scripting.Dictionary")
    low = LCase(body)
    For Each m In NAT_Re(rules("pattern.birth_year"), False).Execute(low)
        years(CLng(m.SubMatches(1))) = 1
    Next
    For Each m In NAT_Re(rules("pattern.birth_numeric"), False).Execute(low)
        years(CLng(m.SubMatches(3))) = 1
        key = NAT_DateKey(CLng(m.SubMatches(3)), CLng(m.SubMatches(2)), CLng(m.SubMatches(1)))
        If key <> "" Then dates(key) = 1
    Next
    For Each m In NAT_Re(rules("pattern.born"), False).Execute(low)
        verbs(m.SubMatches(1)) = 1
        If Len(m.SubMatches(2)) > 0 Then
            years(CLng(m.SubMatches(4))) = 1
            monthNo = NAT_MonthNumber(rules, m.SubMatches(3))
            If monthNo > 0 Then
                key = NAT_DateKey(CLng(m.SubMatches(4)), monthNo, CLng(m.SubMatches(2)))
                If key <> "" Then dates(key) = 1
            End If
        Else
            years(CLng(m.SubMatches(7))) = 1
            key = NAT_DateKey(CLng(m.SubMatches(7)), CLng(m.SubMatches(6)), CLng(m.SubMatches(5)))
            If key <> "" Then dates(key) = 1
        End If
    Next

    If label = "" Then
        where = NAT_Msg(rules, "where.before", Array())
    Else
        where = NAT_Msg(rules, "where.item", Array(label))
    End If
    Set reToken = NAT_Re(rules("pattern.ipn_token"), False)
    For Each m In reToken.Execute(body)
        token = m.SubMatches(1)
        If Not NAT_IpnValid(token) Then
            NAT_Add findings, errorLevel, rule, where, NAT_Msg(rules, "ipn.digit.what", Array()), _
                NAT_Msg(rules, "ipn.digit.how", Array()), token, ""
        Else
            days = CLng(Left(token, 5))
            birth = DateSerial(1899, 12, 31) + days
            sexMale = (CLng(Mid(token, 9, 1)) Mod 2 = 1)
            If dates.Count = 1 Then
                keys = dates.Keys
                onlyDate = keys(0)
                If onlyDate <> NAT_DateKey(Year(birth), Month(birth), Day(birth)) Then
                    NAT_Add findings, warnLevel, rule, where, NAT_Msg(rules, "ipn.date.what", Array(onlyDate)), _
                        NAT_Msg(rules, "ipn.date.how", Array()), token, ""
                End If
            ElseIf years.Count = 1 Then
                keys = years.Keys
                onlyYear = keys(0)
                If Year(birth) <> onlyYear Then
                    NAT_Add findings, warnLevel, rule, where, NAT_Msg(rules, "ipn.year.what", Array(onlyYear)), _
                        NAT_Msg(rules, "ipn.date.how", Array()), token, ""
                End If
            End If
            If verbs.Count = 1 Then
                keys = verbs.Keys
                verb = keys(0)
                If (verb = NAT_Msg(rules, "born.male", Array())) <> sexMale Then
                    NAT_Add findings, warnLevel, rule, where, _
                        NAT_Msg(rules, "ipn.sex.what", Array(UCase(Left(verb, 1)) & Mid(verb, 2))), _
                        NAT_Msg(rules, "ipn.sex.how", Array()), token, ""
                End If
            End If
        End If
    Next
End Sub

' Same split as personnel.ipn_audit: top-level item numbers only.
Sub NAT_CheckIpn(rules, lines, findings)
    Dim reItem, i, label, body, started
    Set reItem = NAT_Re(rules("pattern.ipn_item"), False)
    label = ""
    body = ""
    started = False
    For i = 0 To UBound(lines)
        If reItem.Test(lines(i)) Then
            If started Then NAT_CheckItemIpn rules, label, body, findings
            label = reItem.Execute(lines(i))(0).SubMatches(0)
            body = lines(i)
        ElseIf started Then
            body = body & vbLf & lines(i)
        Else
            body = lines(i)
        End If
        started = True
    Next
    If started Then NAT_CheckItemIpn rules, label, body, findings
End Sub

' Items split like personnel.ipn_audit._split_items: Array(label, body) by top-level number.
Function NAT_IpnItems(rules, lines)
    Dim items, reItem, i, label, body, started
    Set items = CreateObject("Scripting.Dictionary")
    Set reItem = NAT_Re(rules("pattern.ipn_item"), False)
    label = ""
    body = ""
    started = False
    For i = 0 To UBound(lines)
        If reItem.Test(lines(i)) Then
            If started Then items.Add items.Count, Array(label, body)
            label = reItem.Execute(lines(i))(0).SubMatches(0)
            body = lines(i)
        ElseIf started Then
            body = body & vbLf & lines(i)
        Else
            body = lines(i)
        End If
        started = True
    Next
    If started Then items.Add items.Count, Array(label, body)
    Set NAT_IpnItems = items
End Function

Function NAT_ItemWhere(rules, ByVal label)
    If label = "" Then
        NAT_ItemWhere = NAT_Msg(rules, "where.before", Array())
    Else
        NAT_ItemWhere = NAT_Msg(rules, "where.item", Array(label))
    End If
End Function

' ---------------------------------------------------------------- birth year and "u ZS"
' Same as order_review.check.check_bio_format: all birth findings first, then "u ZS".
Sub NAT_CheckBio(rules, lines, findings)
    Dim items, k, label, body, where, reBirth, reStart, reOk, reEnd, m, e, low
    Dim pos, coreLen, core, year, spacing, formOrig, nextCh, rest, fragment, births, services, warnLevel, reAfter
    Set items = NAT_IpnItems(rules, lines)
    Set reBirth = NAT_Re(rules("pattern.birth_mention"), False)
    Set reStart = NAT_Re(rules("pattern.service_start"), False)
    Set reOk = NAT_Re("^(?:" & rules("pattern.service_ok") & ")", False)
    Set reEnd = NAT_Re(rules("pattern.sentence_end"), False)
    ' After "r.n.": a comma, or tabs + RNOKPP + dot in the bio block.
    Set reAfter = NAT_Re("^(?:" & rules("pattern.after_birth") & ")", False)
    Set births = CreateObject("Scripting.Dictionary")
    Set services = CreateObject("Scripting.Dictionary")
    warnLevel = NAT_Msg(rules, "level.warning", Array())
    For Each k In items.Keys
        label = items(k)(0)
        body = items(k)(1)
        where = NAT_ItemWhere(rules, label)
        low = LCase(body)
        For Each m In reBirth.Execute(low)
            pos = m.FirstIndex + Len(m.SubMatches(0))
            coreLen = m.Length - Len(m.SubMatches(0))
            core = Mid(body, pos + 1, coreLen)
            year = m.SubMatches(4)
            spacing = m.SubMatches(5)
            formOrig = Right(core, Len(m.SubMatches(6)))
            nextCh = Mid(body, pos + coreLen + 1)
            If Len(m.SubMatches(1)) > 0 Then
                NAT_Add births, warnLevel, NAT_Msg(rules, "birth.rule", Array()), where, _
                    NAT_Msg(rules, "birth.full.what", Array(core)), NAT_Msg(rules, "birth.full.how", Array(year)), core, ""
            ElseIf (spacing <> " " And spacing <> ChrW(160)) Or formOrig <> NAT_Msg(rules, "birth.good_form", Array()) _
                Or Not reAfter.Test(nextCh) Then
                NAT_Add births, warnLevel, NAT_Msg(rules, "birth.rule", Array()), where, _
                    NAT_Msg(rules, "birth.form.what", Array(core)), NAT_Msg(rules, "birth.form.how", Array(year)), core, ""
            End If
        Next
        For Each m In reStart.Execute(body)
            pos = m.FirstIndex + Len(m.SubMatches(0))
            rest = Mid(body, pos + 1)
            If Not reOk.Test(rest) Then
                ' The fragment never goes past the current line.
                rest = Split(rest & vbLf, vbLf)(0)
                fragment = rest
                If reEnd.Test(rest) Then
                    Set e = reEnd.Execute(rest)(0)
                    fragment = Left(rest, e.FirstIndex + e.Length)
                End If
                fragment = Left(fragment, 60)
                NAT_Add services, warnLevel, NAT_Msg(rules, "service.rule", Array()), where, _
                    NAT_Msg(rules, "service.what", Array(fragment)), NAT_Msg(rules, "service.how", Array()), fragment, ""
            End If
        Next
    Next
    For Each k In births.Keys
        findings.Add findings.Count, births(k)
    Next
    For Each k In services.Keys
        findings.Add findings.Count, services(k)
    Next
End Sub

' ---------------------------------------------------------------- doubled marks and spaces
Function NAT_Around(ByVal ln, ByVal s, ByVal e)
    Dim st
    st = s - 20
    If st < 0 Then st = 0
    NAT_Around = Mid(ln, st + 1, e + 10 - st)
End Function

Sub NAT_CheckDoubles(rules, lines, findings)
    Dim items, k, where, parts, j, ln, m, s, reDots, reMarks, reSpaces, warnLevel, rule
    Set items = NAT_IpnItems(rules, lines)
    Set reDots = NAT_Re("(^|[^.])(\.\.)(?!\.)", False)
    Set reMarks = NAT_Re("([,;:!?])\1+", False)
    Set reSpaces = NAT_Re("(\S)(  )(?=\S)", False)
    warnLevel = NAT_Msg(rules, "level.warning", Array())
    rule = NAT_Msg(rules, "doubles.rule", Array())
    For Each k In items.Keys
        where = NAT_ItemWhere(rules, items(k)(0))
        parts = Split(items(k)(1), vbLf)
        For j = 0 To UBound(parts)
            ln = parts(j)
            For Each m In reDots.Execute(ln)
                s = m.FirstIndex + Len(m.SubMatches(0))
                NAT_Add findings, warnLevel, rule, where, NAT_Msg(rules, "doubles.mark.what", Array("..")), _
                    NAT_Msg(rules, "doubles.mark.how", Array()), NAT_Around(ln, s, s + 2), ""
            Next
            For Each m In reMarks.Execute(ln)
                NAT_Add findings, warnLevel, rule, where, NAT_Msg(rules, "doubles.mark.what", Array(m.Value)), _
                    NAT_Msg(rules, "doubles.mark.how", Array()), NAT_Around(ln, m.FirstIndex, m.FirstIndex + m.Length), ""
            Next
            For Each m In reSpaces.Execute(ln)
                s = m.FirstIndex + 1
                NAT_Add findings, warnLevel, rule, where, NAT_Msg(rules, "doubles.space.what", Array()), _
                    NAT_Msg(rules, "doubles.space.how", Array()), NAT_Around(ln, s, s + 2), ""
            Next
        Next
    Next
End Sub

' ---------------------------------------------------------------- two empty paragraphs before the signer
Sub NAT_CheckSignerSpacing(rules, lines, findings)
    Dim start, i, lastItem, reItem, reSigner, blanks
    Set reItem = NAT_Re(rules("pattern.item"), False)
    Set reSigner = NAT_Re(rules("pattern.signer"), False)
    start = NAT_ContentStart(rules, lines)
    lastItem = -1
    For i = start To UBound(lines)
        If reItem.Test(NAT_Strip(lines(i))) Then lastItem = i
    Next
    If lastItem < 0 Then Exit Sub
    For i = lastItem + 1 To UBound(lines)
        If reSigner.Test(LCase(NAT_Strip(lines(i)))) Then
            blanks = 0
            Do While i - blanks - 1 > lastItem
                If NAT_Strip(lines(i - blanks - 1)) <> "" Then Exit Do
                blanks = blanks + 1
            Loop
            If blanks <> 2 Then
                NAT_Add findings, NAT_Msg(rules, "level.warning", Array()), NAT_Msg(rules, "signer.rule", Array()), _
                    NAT_Msg(rules, "signer.where", Array()), NAT_Msg(rules, "signer.what", Array(blanks)), _
                    NAT_Msg(rules, "signer.how", Array()), Left(NAT_Strip(lines(i)), 60), ""
            End If
            Exit Sub
        End If
    Next
End Sub

' ---------------------------------------------------------------- items with a person
' Same as order_index.items.iter_items over order_index.extractor.iter_blocks.
Function NAT_Items(rules, lines)
    Dim items, rePerson, reSection, reHeading, reLabel, reCapWord
    Dim i, text, buffer, start, section, blockText, current, m, label, body, personStart, rank
    Set items = CreateObject("Scripting.Dictionary")
    Set rePerson = NAT_Re(rules("pattern.person"), False)
    Set reSection = NAT_Re(rules("pattern.section"), False)
    Set reHeading = NAT_Re(rules("pattern.heading"), False)
    Set reLabel = NAT_Re(rules("pattern.item_label"), False)
    Set reCapWord = NAT_Re(rules("pattern.last_cap_word"), False)
    Set current = Nothing
    section = ""
    buffer = ""
    start = 0
    For i = 0 To UBound(lines) + 1
        blockText = ""
        If i > UBound(lines) Then
            blockText = buffer
            buffer = ""
        Else
            text = NAT_NormalizeSpace(lines(i))
            If text <> "" Then
                If reSection.Test(text) Then
                    blockText = buffer
                    buffer = ""
                    ' The section itself is applied after the pending block is flushed.
                Else
                    If buffer = "" Then
                        start = i
                        buffer = text
                    Else
                        buffer = buffer & " " & text
                    End If
                    If Right(text, 1) = "." Or Right(text, 1) = ":" Or Right(text, 1) = ";" Then
                        blockText = buffer
                        buffer = ""
                    End If
                End If
            End If
        End If
        If blockText <> "" Then
            If rePerson.Test(blockText) Then
                label = ""
                body = blockText
                If reLabel.Test(blockText) Then
                    Set m = reLabel.Execute(blockText)(0)
                    label = m.SubMatches(0)
                    body = Mid(blockText, m.FirstIndex + m.Length + 1)
                End If
                Set m = rePerson.Execute(body)(0)
                personStart = m.FirstIndex + Len(m.SubMatches(0))
                rank = NAT_StripChars(NAT_NormalizeSpace(Left(body, personStart)), " ,")
                If reCapWord.Test(rank) Then rank = reCapWord.Execute(rank)(0).SubMatches(1)
                Set current = CreateObject("Scripting.Dictionary")
                current("section") = section
                current("label") = label
                current("paragraph") = start
                current("rank") = rank
                current("text") = body
                current("person_end") = personStart + Len(m.SubMatches(1))
                current("person") = m.SubMatches(1)
                items.Add items.Count, current
            ElseIf reHeading.Test(LCase(blockText)) Then
                Set current = Nothing
            ElseIf Not current Is Nothing Then
                current("text") = current("text") & vbLf & blockText
            End If
        End If
        If i <= UBound(lines) Then
            text = NAT_NormalizeSpace(lines(i))
            If text <> "" Then
                If reSection.Test(text) Then
                    section = Left(text, 12)
                    Set current = Nothing
                End If
            End If
        End If
    Next
    Set NAT_Items = items
End Function

' ---------------------------------------------------------------- nomenclature
Function NAT_HeadingContext(rules, lines, ByVal paragraph)
    Dim i, clean, out, reItem, reHint
    Set reItem = NAT_Re(rules("pattern.item"), False)
    Set reHint = NAT_Re(rules("pattern.hint"), False)
    out = ""
    For i = paragraph - 1 To 0 Step -1
        clean = NAT_Strip(lines(i))
        If Left(clean, 1) = ChrW(167) Then Exit For
        If clean <> "" Then
            If Not reItem.Test(clean) And reHint.Test(LCase(clean)) Then
                If out = "" Then
                    out = clean
                Else
                    out = clean & vbLf & out
                End If
            End If
        End If
    Next
    NAT_HeadingContext = out
End Function

Function NAT_OrderAction(rules, ByVal text)
    Dim clean
    clean = LCase(NAT_NormalizeSpace(text))
    If NAT_Re(rules("pattern.dismissal"), False).Test(clean) Then
        NAT_OrderAction = NAT_Msg(rules, "action.dismissal", Array())
    ElseIf InStr(clean, NAT_Msg(rules, "action.appoint_verb", Array())) > 0 Then
        NAT_OrderAction = NAT_Msg(rules, "action.appointment", Array())
    Else
        NAT_OrderAction = ""
    End If
End Function

Function NAT_FirstLine(ByVal text)
    NAT_FirstLine = Left(Split(text & vbLf, vbLf)(0), 60)
End Function

Sub NAT_CheckNomenclature(rules, lines, items, findings)
    Dim limits, i, parts, k, item, context, action, limit, maxLevel, maxName, navalAllowed, basis
    Dim candidates, labels, m, c, rank, level, errorLevel, warnLevel, rule, navals, j, isNaval, where
    Set limits = CreateObject("Scripting.Dictionary")
    For i = 1 To rules("limit.count")
        parts = Split(rules("limit." & i), "|")
        limits.Add parts(0), parts
    Next
    If limits.Count = 0 Then Exit Sub
    errorLevel = NAT_Msg(rules, "level.error", Array())
    warnLevel = NAT_Msg(rules, "level.warning", Array())
    rule = NAT_Msg(rules, "nom.rule", Array())
    navals = Split(rules("naval"), "|")
    For Each k In items.Keys
        Set item = items(k)
        context = NAT_HeadingContext(rules, lines, item("paragraph"))
        action = NAT_OrderAction(rules, context & vbLf & item("text"))
        limit = Empty
        If limits.Exists(action) Then
            limit = limits(action)
        ElseIf limits.Exists(NAT_Msg(rules, "action.any", Array())) Then
            limit = limits(NAT_Msg(rules, "action.any", Array()))
        End If
        If Not IsEmpty(limit) Then
            ' Empty limit = rank not limited (appointment, transfer); naval rule still applies.
            maxLevel = 999
            If limit(1) <> "" Then maxLevel = CLng(limit(1))
            maxName = limit(2)
            navalAllowed = (limit(3) = "1")
            basis = limit(4)
            where = NAT_Place(rules, item("label"))
            candidates = item("rank")
            labels = NAT_Msg(rules, "nom.label.person", Array())
            For Each m In NAT_Re(rules("pattern.quoted"), False).Execute(item("text"))
                candidates = candidates & vbTab & m.SubMatches(0)
                labels = labels & vbTab & NAT_Msg(rules, "nom.label.quoted", Array())
            Next
            candidates = Split(candidates, vbTab)
            labels = Split(labels, vbTab)
            For c = 0 To UBound(candidates)
                rank = candidates(c)
                level = NAT_RankLevel(rules, rank)
                If level > maxLevel Then
                    NAT_Add findings, errorLevel, rule, where, _
                        NAT_Msg(rules, "nom.over.what", Array(labels(c), NAT_Strip(rank), maxName, _
                            NAT_Msg(rules, "nom.action." & action, Array()))), _
                        basis, NAT_Strip(rank), NAT_FirstLine(item("text"))
                End If
                isNaval = False
                For j = 0 To UBound(navals)
                    If InStr(LCase(rank), navals(j)) > 0 Then isNaval = True
                Next
                ' Naval ranks: off in the macro (check.naval=0) - orders are Ground Forces only.
                If rules("check.naval") = "1" And Not navalAllowed And rank <> "" And isNaval And level >= 0 Then
                    NAT_Add findings, warnLevel, rule, where, _
                        NAT_Msg(rules, "nom.naval.what", Array(labels(c), NAT_Strip(rank))), _
                        NAT_Msg(rules, "nom.naval.how", Array()), NAT_Strip(rank), NAT_FirstLine(item("text"))
                End If
            Next
        End If
    Next
End Sub

' ---------------------------------------------------------------- alphabetical order
' Same as order_review.check.alphabet_key: letters of the stem as positions in the
' Ukrainian alphabet (2 digits), "99" for other letters, "00" between words.
Function NAT_AlphaKey(rules, ByVal words)
    Dim alphabet, out, w, s, i, ch, idx
    alphabet = rules("alphabet")
    out = ""
    For w = 0 To 2
        s = ""
        If w <= UBound(words) Then s = NAT_Stem(rules, words(w))
        For i = 1 To Len(s)
            ch = Mid(s, i, 1)
            idx = InStr(alphabet, ch)
            If idx > 0 Then
                out = out & Right("0" & idx, 2)
            ElseIf UCase(ch) <> LCase(ch) Then
                out = out & "99"
            End If
        Next
        out = out & "00"
    Next
    NAT_AlphaKey = out
End Function

Function NAT_PersonWords(ByVal person)
    NAT_PersonWords = Split(NAT_NormalizeSpace(Replace(person, ",", " ")), " ")
End Function

' A heading between two items starts a new group: section, "Vidpovidno do ...:", CAPS line.
Function NAT_StartsNewGroup(rules, lines, ByVal previous, ByVal current)
    Dim i, clean, reHint, j, ch, hasLetter, hasLower
    Set reHint = NAT_Re(rules("pattern.hint"), False)
    NAT_StartsNewGroup = False
    For i = previous + 1 To current - 1
        clean = NAT_Strip(lines(i))
        If clean <> "" Then
            If Left(clean, 1) = ChrW(167) Or reHint.Test(LCase(clean)) Then
                NAT_StartsNewGroup = True
                Exit Function
            End If
            hasLetter = False
            hasLower = False
            For j = 1 To Len(clean)
                ch = Mid(clean, j, 1)
                If UCase(ch) <> LCase(ch) Then
                    hasLetter = True
                    If ch = LCase(ch) Then hasLower = True
                End If
            Next
            If hasLetter And Not hasLower Then
                NAT_StartsNewGroup = True
                Exit Function
            End If
        End If
    Next
End Function

Sub NAT_CheckAlphabet(rules, lines, items, findings)
    Dim k, item, previous, words, previousWords, hasPrevious
    hasPrevious = False
    For Each k In items.Keys
        Set item = items(k)
        If InStr(item("label"), ".") = 0 Then
            words = NAT_PersonWords(item("person"))
            If hasPrevious Then
                If previous("section") = item("section") Then
                    If Not NAT_StartsNewGroup(rules, lines, previous("paragraph"), item("paragraph")) Then
                        previousWords = NAT_PersonWords(previous("person"))
                        If NAT_AlphaKey(rules, previousWords) > NAT_AlphaKey(rules, words) Then
                            NAT_Add findings, NAT_Msg(rules, "level.warning", Array()), _
                                NAT_Msg(rules, "alpha.rule", Array()), NAT_Place(rules, item("label")), _
                                NAT_Msg(rules, "alpha.what", Array(words(0), previousWords(0))), _
                                NAT_Msg(rules, "alpha.how", Array()), NAT_FirstLine(item("text")), ""
                        End If
                    End If
                End If
            End If
            Set previous = item
            hasPrevious = True
        End If
    Next
End Sub

' ---------------------------------------------------------------- position spelling
' Simplified vs the program: the first two words of the current and of the new
' position (those carry the position name; later words are units and places).
Function NAT_Distance(ByVal a, ByVal b)
    Dim la, lb, i, j, prev(), cur(), cost, best
    la = Len(a)
    lb = Len(b)
    ReDim prev(lb)
    ReDim cur(lb)
    For j = 0 To lb
        prev(j) = j
    Next
    For i = 1 To la
        cur(0) = i
        For j = 1 To lb
            cost = 1
            If Mid(a, i, 1) = Mid(b, j, 1) Then cost = 0
            best = prev(j) + 1
            If cur(j - 1) + 1 < best Then best = cur(j - 1) + 1
            If prev(j - 1) + cost < best Then best = prev(j - 1) + cost
            cur(j) = best
        Next
        For j = 0 To lb
            prev(j) = cur(j)
        Next
    Next
    NAT_Distance = prev(lb)
End Function

Function NAT_Suggest(rules, ByVal word)
    Dim words, w, d, bestWord, bestD
    Set words = rules("words")
    bestD = 3
    bestWord = ""
    For Each w In words.Keys
        If Abs(Len(w) - Len(word)) <= 2 Then
            d = NAT_Distance(word, w)
            If d < bestD Then
                bestD = d
                bestWord = w
            End If
        End If
    Next
    NAT_Suggest = bestWord
End Function

Sub NAT_CheckWords(rules, ByVal positionText, ByVal where, ByVal firstLine, findings)
    Dim reWord, m, checked, word, suggestion, how, vocab
    Set vocab = rules("vocab")
    Set reWord = NAT_Re(rules("pattern.word"), False)
    checked = 0
    For Each m In reWord.Execute(positionText)
        word = m.Value
        If checked >= 2 Then Exit For
        If Not IsNumeric(word) Then
            checked = checked + 1
            If Len(word) >= 3 And Not vocab.Exists(NAT_Stem(rules, word)) Then
                suggestion = NAT_Suggest(rules, LCase(word))
                If suggestion <> "" Then
                    how = NAT_Msg(rules, "spell.how_suggest", Array(suggestion))
                Else
                    how = NAT_Msg(rules, "spell.how_none", Array())
                End If
                NAT_Add findings, NAT_Msg(rules, "level.warning", Array()), NAT_Msg(rules, "spell.rule", Array()), _
                    where, NAT_Msg(rules, "spell.what", Array(NAT_NormalizeSpace(positionText), LCase(word))), _
                    how, word, firstLine
            End If
        End If
    Next
End Sub

Sub NAT_CheckSpelling(rules, items, findings)
    Dim k, item, rest, reCaps, m, capsStart, current, target, tokens, t, where, stopAt, verbs, verbEnd, p
    Set reCaps = NAT_Re(rules("pattern.caps_word"), False)
    For Each k In items.Keys
        Set item = items(k)
        where = NAT_Place(rules, item("label"))
        rest = Split(Mid(item("text"), item("person_end") + 1) & vbLf, vbLf)(0)
        capsStart = Len(rest) + 1
        If reCaps.Test(rest) Then
            Set m = reCaps.Execute(rest)(0)
            capsStart = m.FirstIndex + Len(m.SubMatches(0)) + 1
        End If
        current = Left(rest, capsStart - 1)
        stopAt = InStr(current, ". ")
        If stopAt > 0 Then current = Left(current, stopAt - 1)
        If Len(NAT_Strip(current)) > 0 Then
            If Not IsNumeric(Left(NAT_Strip(current), 1)) Then
                NAT_CheckWords rules, current, where, NAT_FirstLine(item("text")), findings
            End If
        End If
        ' New position: the first CAPS run that is not an order verb (...TY) or a preposition.
        target = ""
        tokens = Split(NAT_NormalizeSpace(Mid(rest, capsStart)), " ")
        For t = 0 To UBound(tokens)
            p = NAT_StripChars(tokens(t), ",.;:")
            If p = "" Then Exit For
            If LCase(p) = p Then Exit For
            If Right(p, 2) = NAT_Msg(rules, "verb.ending", Array()) And target = "" Then
                ' skip the order verb itself
            Else
                target = target & " " & p
            End If
            If Right(tokens(t), 1) = "." Or Right(tokens(t), 1) = ";" Then Exit For
        Next
        target = NAT_Strip(target)
        If target <> "" Then
            If InStr(" " & NAT_Msg(rules, "not_position_start", Array()) & " ", " " & Split(target, " ")(0) & " ") = 0 Then
                NAT_CheckWords rules, target, where, NAT_FirstLine(item("text")), findings
            End If
        End If
    Next
End Sub

' ---------------------------------------------------------------- entry
Function NAT_Review(rules, ByVal text)
    Dim findings, lines, start, items, sliced, i
    Set findings = CreateObject("Scripting.Dictionary")
    lines = NAT_SplitLines(text)
    NAT_CheckNumbering rules, lines, findings
    NAT_CheckIpn rules, lines, findings
    NAT_CheckBio rules, lines, findings
    NAT_CheckDoubles rules, lines, findings
    NAT_CheckSignerSpacing rules, lines, findings
    start = NAT_ContentStart(rules, lines)
    If UBound(lines) >= start Then
        ReDim sliced(UBound(lines) - start)
        For i = start To UBound(lines)
            sliced(i - start) = lines(i)
        Next
    Else
        sliced = Array()
    End If
    Set items = NAT_Items(rules, sliced)
    NAT_CheckNomenclature rules, sliced, items, findings
    NAT_CheckAlphabet rules, sliced, items, findings
    If rules("check.spelling") = "1" Then NAT_CheckSpelling rules, items, findings
    Set NAT_Review = findings
End Function

Function NAT_FindingsText(findings)
    Dim k, out
    out = ""
    For Each k In findings.Keys
        out = out & findings(k) & vbLf
    Next
    NAT_FindingsText = out
End Function
'=== NAT CORE END ===

' ---------------------------------------------------------------- Word side
' Text of the document by paragraphs, with Word auto-numbers ("1.", "2)") put
' in front - the same as read_document_text in the program.
Function NAT_DocumentText(doc) As String
    Dim p As Object, t As String, ls As String, parts() As String, n As Long
    Dim reNumber As Object, reDigit As Object
    Set reNumber = NAT_Re("^[0-9]{1,3}(\.[0-9]{1,3})*[.)]$", False)
    Set reDigit = NAT_Re("^\s*[0-9]", False)
    ReDim parts(doc.Paragraphs.Count)
    n = 0
    For Each p In doc.Paragraphs
        t = p.Range.Text
        Do While Len(t) > 0 And (Right(t, 1) = vbCr Or Right(t, 1) = Chr(7))
            t = Left(t, Len(t) - 1)
        Loop
        ls = ""
        On Error Resume Next
        ls = p.Range.ListFormat.ListString
        On Error GoTo 0
        If ls <> "" Then
            If reNumber.Test(ls) And Not reDigit.Test(t) Then t = ls & " " & t
        End If
        parts(n) = t
        n = n + 1
    Next
    If n > 0 Then ReDim Preserve parts(n - 1)
    NAT_DocumentText = Join(parts, vbLf)
End Function

Function NAT_FindRange(doc, ByVal q1 As String, ByVal q2 As String) As Object
    Dim quotes As Variant, i As Long, needle As String, r As Object
    Set NAT_FindRange = Nothing
    quotes = Array(q1, q2)
    For i = 0 To 1
        needle = Left(NAT_NormalizeSpace(CStr(quotes(i))), 200)
        If Len(needle) >= 3 Then
            Set r = doc.Content
            With r.Find
                .ClearFormatting
                .Text = Replace(needle, "^", "^^")
                .MatchCase = True
                .MatchWholeWord = False
                .MatchWildcards = False
                .Forward = True
                .Wrap = 0
                If .Execute Then
                    Set NAT_FindRange = r
                    Exit Function
                End If
            End With
        End If
    Next
End Function

' Short word or number at the END of a wrapped line (Word layout, so it lives here,
' not in the core). At the start of a line it is fine; a paragraph end is not a wrap.
' Bio block (left indent 4 cm and more, towards the centre) is not checked.
' A word is at the end of a line when the next word of the same paragraph has another
' line number (Information(wdFirstCharacterLineNumber = 10)) or page (3). Checked in
' real Word: works with a hidden window too, no view switching needed.
' Returns Dictionary: Array(range, tsv line).
Function NAT_LineEnds(doc, rules) As Object
    Dim result As Object, shortWords As Object, w As Variant, para As Object, ws As Object
    Dim i As Long, n As Long, wr As Object, nx As Object, token As String, tr As Object
    Dim what As String, reNumber As Object, bioIndent As Single, nextText As String
    Set result = CreateObject("Scripting.Dictionary")
    Set NAT_LineEnds = result
    Set shortWords = CreateObject("Scripting.Dictionary")
    For Each w In Split(rules("short_words"), "|")
        shortWords(w) = 1
    Next
    Set reNumber = NAT_Re("^[0-9]+$", False)
    bioIndent = Application.CentimetersToPoints(4)
    On Error GoTo done
    For Each para In doc.Paragraphs
        If para.LeftIndent < bioIndent Then
            Set ws = para.Range.Words
            n = ws.Count
            For i = 1 To n - 1
                Set wr = ws(i)
                token = Trim(wr.Text)
                what = ""
                If shortWords.Exists(LCase(token)) Then
                    what = NAT_Msg(rules, "lineend.word.what", Array(token))
                ElseIf reNumber.Test(token) Then
                    what = NAT_Msg(rules, "lineend.number.what", Array(token))
                End If
                If what <> "" Then
                    Set nx = ws(i + 1)
                    nextText = nx.Text
                    If nextText <> vbCr And nextText <> Chr(7) And nextText <> Chr(11) Then
                        If wr.Information(10) <> nx.Information(10) Or wr.Information(3) <> nx.Information(3) Then
                            Set tr = doc.Range(wr.Start, wr.Start + Len(token))
                            result.Add result.Count, Array(tr, Join(Array( _
                                NAT_Msg(rules, "level.warning", Array()), NAT_Msg(rules, "lineend.rule", Array()), _
                                NAT_Msg(rules, "lineend.where", Array(tr.Information(3))), what, _
                                NAT_Msg(rules, "lineend.how", Array(token)), token, ""), vbTab))
                        End If
                    End If
                End If
            Next
        End If
    Next
done:
End Function

' Old NAT comments are removed first, then warnings (yellow) and errors (red) are
' added - errors last, so red is never covered by yellow on the same place.
' Line ends are found before any mark is added (marks must not move the layout).
Sub NAT_ApplyFindings(doc, findings, rules, ByVal notes As String)
    Dim i As Long, pass As Long, k As Variant, f() As String, r As Object, errorLevel As String
    Dim errors As Long, warnings As Long, message As String, lineEnds As Object
    For i = doc.Comments.Count To 1 Step -1
        If Left(doc.Comments(i).Range.Text, 6) = "[NAT] " Then
            doc.Comments(i).Scope.HighlightColorIndex = 0
            doc.Comments(i).Delete
        End If
    Next
    Set lineEnds = NAT_LineEnds(doc, rules)
    For Each k In lineEnds.Keys
        Set r = lineEnds(k)(0)
        f = Split(lineEnds(k)(1), vbTab)
        r.HighlightColorIndex = 7
        doc.Comments.Add r, "[NAT] " & UCase(f(0)) & " " & ChrW(183) & " " & f(1) & ": " & f(2) & ", " & f(3) & ". " & f(4)
        warnings = warnings + 1
    Next
    errorLevel = NAT_Msg(rules, "level.error", Array())
    For pass = 0 To 1
        For Each k In findings.Keys
            f = Split(findings(k), vbTab)
            If (f(0) = errorLevel) = (pass = 1) Then
                Set r = NAT_FindRange(doc, f(5), f(6))
                If r Is Nothing Then
                    Set r = doc.Range(0, 0)
                ElseIf pass = 1 Then
                    r.HighlightColorIndex = 6
                Else
                    r.HighlightColorIndex = 7
                End If
                message = "[NAT] " & UCase(f(0)) & " " & ChrW(183) & " " & f(1) & ": " & f(2) & ", " & f(3) & "."
                If f(4) <> "" Then message = message & " " & f(4)
                doc.Comments.Add r, message
                If pass = 1 Then errors = errors + 1 Else warnings = warnings + 1
            End If
        Next
    Next
    If errors + warnings = 0 Then
        message = NAT_Msg(rules, "done.clean", Array())
    Else
        message = NAT_Msg(rules, "done.summary", Array(errors, warnings)) & vbLf & vbLf & _
            NAT_Msg(rules, "done.note", Array())
    End If
    If notes <> "" Then message = message & vbLf & vbLf & notes
    MsgBox message, vbInformation, NAT_Msg(rules, "done.title", Array())
End Sub

' nat_rules.txt: remembered path, next to this template, or asked once.
Function NAT_RulesPath() As String
    Dim path As String, fso As Object
    Set fso = CreateObject("Scripting.FileSystemObject")
    path = GetSetting("NATCheck", "Paths", "Rules", "")
    If path <> "" Then
        If fso.FileExists(path) Then
            NAT_RulesPath = path
            Exit Function
        End If
    End If
    On Error Resume Next
    path = MacroContainer.Path & "\nat_rules.txt"
    On Error GoTo 0
    If fso.FileExists(path) Then
        NAT_RulesPath = path
        Exit Function
    End If
    With Application.FileDialog(3)
        .Title = "nat_rules.txt"
        .AllowMultiSelect = False
        .Filters.Clear
        .Filters.Add "NAT rules", "*.txt"
        If .Show = -1 Then
            path = .SelectedItems(1)
            SaveSetting "NATCheck", "Paths", "Rules", path
            NAT_RulesPath = path
        End If
    End With
End Function

Public Sub NAT_CheckOrderOffline()
    Dim path As String, rules As Object, findings As Object
    path = NAT_RulesPath()
    If path = "" Then Exit Sub
    Set rules = NAT_LoadRules(path)
    Set findings = NAT_Review(rules, NAT_DocumentText(ActiveDocument))
    NAT_ApplyFindings ActiveDocument, findings, rules, ""
End Sub
